name: Deploy React App Infra + Code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ENV_NAME: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Set environment
        run: echo "Deploying to $ENV_NAME"

      - name: Deploy infrastructure
        run: |
          sam build
          sam deploy --no-confirm-changeset \
            --stack-name react-app-${{ env.ENV_NAME }} \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides EnvName=${{ env.ENV_NAME }} || exit 0

      - name: Fetch CloudFormation Outputs
        id: outputs
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name react-app-${{ env.ENV_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" \
            --output text)

          DISTRIBUTION_ID=$(aws cloudformation describe-stacks \
            --stack-name react-app-${{ env.ENV_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='DistributionId'].OutputValue" \
            --output text)

          echo "bucket=$BUCKET_NAME" >> $GITHUB_OUTPUT
          echo "distribution_id=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://${{ steps.outputs.outputs.bucket }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ steps.outputs.outputs.distribution_id }} \
            --paths "/*"
